services:
  - type: web
    name: ai-book-reader
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: |
      cd backend && uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
